### ISSUE TITLE
Socket close while disposition batcher sends causes dead lock

### ISSUE THREAD

**Issue by mcardy** [Azure/go-amqp#216]
Observed when the server socket is closed (e.g. toxiproxy `down`, management disconnect, etc.) while a batched disposition is sending. ReceiveMessage hangs forever after this. `kill -3` response:
```
goroutine 1355 [select, 918 minutes]:
runtime.gopark(0xc001f3be50?, 0x2?, 0xc8?, 0x23?, 0xc001f3be24?)
      runtime/proc.go:363 +0xd6 fp=0xc001f3bcb0 sp=0xc001f3bc90 pc=0x43d2b6
runtime.selectgo(0xc001f3be50, 0xc001f3be20, 0x20?, 0x1, 0x28?, 0x1)
      runtime/select.go:328 +0x7bc fp=0xc001f3bdf0 sp=0xc001f3bcb0 pc=0x44d1fc
github.com/Azure/go-amqp.(*Conn).sendFrame(...)
      github.com/Azure/go-amqp@v0.18.0/conn.go:809
github.com/Azure/go-amqp.(*Session).txFrame(0x0?, {0x7778360?, 0xc002594360?}, 0x40e127?)
      github.com/Azure/go-amqp@v0.18.0/session.go:188 +0xaa fp=0xc001f3be80 sp=0xc001f3bdf0 pc=0x3469d8a
github.com/Azure/go-amqp.(*Receiver).sendDisposition(0xc0004e0000, 0x251c, 0xc001cd6ad0, {0x7778240?, 0xb7e0040})
      github.com/Azure/go-amqp@v0.18.0/receiver.go:341 +0x116 fp=0xc001f3bec8 sp=0xc001f3be80 pc=0x34628d6
github.com/Azure/go-amqp.(*Receiver).dispositionBatcher(0xc0004e0000)
      github.com/Azure/go-amqp@v0.18.0/receiver.go:300 +0x25d fp=0xc001f3bfc8 sp=0xc001f3bec8 pc=0x34624bd
github.com/Azure/go-amqp.(*Session).NewReceiver.func1()
      github.com/Azure/go-amqp@v0.18.0/session.go:216 +0x26 fp=0xc001f3bfe0 sp=0xc001f3bfc8 pc=0x3469fc6
runtime.goexit()
      runtime/asm_amd64.s:1594 +0x1 fp=0xc001f3bfe8 sp=0xc001f3bfe0 pc=0x46f181
created by github.com/Azure/go-amqp.(*Session).NewReceiver
      github.com/Azure/go-amqp@v0.18.0/session.go:216 +0x10a

goroutine 1742 [select, 918 minutes]:
runtime.gopark(0xc0026c6998?, 0x2?, 0x11?, 0xe0?, 0xc0026c696c?)
      runtime/proc.go:363 +0xd6 fp=0xc0026c67f8 sp=0xc0026c67d8 pc=0x43d2b6
runtime.selectgo(0xc0026c6998, 0xc0026c6968, 0x100c0026c6ca8?, 0x1, 0x0?, 0x1)
      runtime/select.go:328 +0x7bc fp=0xc0026c6938 sp=0xc0026c67f8 pc=0x44d1fc
github.com/Azure/go-amqp.(*Conn).sendFrame(...)
      github.com/Azure/go-amqp@v0.18.0/conn.go:809
github.com/Azure/go-amqp.(*Session).txFrame(0xc0026c6e78?, {0x77783a0?, 0xc0017f6780?}, 0x0?)
      github.com/Azure/go-amqp@v0.18.0/session.go:188 +0xaa fp=0xc0026c69c8 sp=0xc0026c6938 pc=0x3469d8a
github.com/Azure/go-amqp.(*Session).mux(0xc000966640, 0xc0022f2000)
      github.com/Azure/go-amqp@v0.18.0/session.go:553 +0xfc5 fp=0xc0026c6fc0 sp=0xc0026c69c8 pc=0x346b0a5
github.com/Azure/go-amqp.(*Session).begin.func2()
      github.com/Azure/go-amqp@v0.18.0/session.go:161 +0x2a fp=0xc0026c6fe0 sp=0xc0026c6fc0 pc=0x34699aa
runtime.goexit()
      runtime/asm_amd64.s:1594 +0x1 fp=0xc0026c6fe8 sp=0xc0026c6fe0 pc=0x46f181
created by github.com/Azure/go-amqp.(*Session).begin
      github.com/Azure/go-amqp@v0.18.0/session.go:161 +0x1df

goroutine 1353 [select, 918 minutes]:
runtime.gopark(0xc001f38f20?, 0x2?, 0xa0?, 0xec?, 0xc001f38e54?)
      runtime/proc.go:363 +0xd6 fp=0xc001f38c90 sp=0xc001f38c70 pc=0x43d2b6
runtime.selectgo(0xc001f38f20, 0xc001f38e50, 0xc002100338?, 0x1, 0x4c6fc5df00000000?, 0x1)
      runtime/select.go:328 +0x7bc fp=0xc001f38dd0 sp=0xc001f38c90 pc=0x44d1fc
github.com/Azure/go-amqp.(*Conn).connReader(0xc0017da2c0)
      github.com/Azure/go-amqp@v0.18.0/conn.go:692 +0x589 fp=0xc001f38fc8 sp=0xc001f38dd0 pc=0x345bb69
github.com/Azure/go-amqp.(*Conn).start.func1()
      github.com/Azure/go-amqp@v0.18.0/conn.go:334 +0x26 fp=0xc001f38fe0 sp=0xc001f38fc8 pc=0x345a1a6
runtime.goexit()
      runtime/asm_amd64.s:1594 +0x1 fp=0xc001f38fe8 sp=0xc001f38fe0 pc=0x46f181
created by github.com/Azure/go-amqp.(*Conn).start
      github.com/Azure/go-amqp@v0.18.0/conn.go:334 +0x5a

goroutine 1752 [select, 918 minutes]:
runtime.gopark(0xc001f37e68?, 0x2?, 0x9?, 0x18?, 0xc001f37dd8?)
      runtime/proc.go:363 +0xd6 fp=0xc001f37c60 sp=0xc001f37c40 pc=0x43d2b6
runtime.selectgo(0xc001f37e68, 0xc001f37dd4, 0xc001f37e08?, 0x1, 0x0?, 0x1)
      runtime/select.go:328 +0x7bc fp=0xc001f37da0 sp=0xc001f37c60 pc=0x44d1fc
github.com/Azure/go-amqp.(*Conn).mux(0xc0017da2c0)
      github.com/Azure/go-amqp@v0.18.0/conn.go:537 +0x868 fp=0xc001f37fc8 sp=0xc001f37da0 pc=0x345b3c8
github.com/Azure/go-amqp.(*Conn).start.func2()
      github.com/Azure/go-amqp@v0.18.0/conn.go:353 +0x26 fp=0xc001f37fe0 sp=0xc001f37fc8 pc=0x345a146
runtime.goexit()
      runtime/asm_amd64.s:1594 +0x1 fp=0xc001f37fe8 sp=0xc001f37fe0 pc=0x46f181
created by github.com/Azure/go-amqp.(*Conn).start
      github.com/Azure/go-amqp@v0.18.0/conn.go:353 +0x15b

goroutine 1354 [select, 918 minutes]:
runtime.gopark(0xc00185cf70?, 0x4?, 0x60?, 0xbe?, 0xc00185cf08?)
      runtime/proc.go:363 +0xd6 fp=0xc00185cd88 sp=0xc00185cd68 pc=0x43d2b6
runtime.selectgo(0xc00185cf70, 0xc00185cf00, 0xc0017d3900?, 0x0, 0xc0000fe501?, 0x1)
      runtime/select.go:328 +0x7bc fp=0xc00185cec8 sp=0xc00185cd88 pc=0x44d1fc
github.com/Azure/go-amqp.(*Receiver).mux(0xc0004e0000)
      github.com/Azure/go-amqp@v0.18.0/receiver.go:580 +0x388 fp=0xc00185cfc8 sp=0xc00185cec8 pc=0x3464208
github.com/Azure/go-amqp.(*Receiver).attach.func3()
      github.com/Azure/go-amqp@v0.18.0/receiver.go:534 +0x26 fp=0xc00185cfe0 sp=0xc00185cfc8 pc=0x3463c26
runtime.goexit()
      runtime/asm_amd64.s:1594 +0x1 fp=0xc00185cfe8 sp=0xc00185cfe0 pc=0x46f181
created by github.com/Azure/go-amqp.(*Receiver).attach
      github.com/Azure/go-amqp@v0.18.0/receiver.go:534 +0x13c

rax    0xca
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xb7e2d40
rsi    0x80
rbp    0xc0002f1718
rsp    0xc0002f16d0
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc0000c0500
r13    0x4
r14    0xc000dcb380
r15    0x7fb5d33eb5a9
rip    0x4710c1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```
And on the main thread
```
goroutine 92 [select, 918 minutes]:
runtime.gopark(0xc001e438f0?, 0x3?, 0xf8?, 0x38?, 0xc001e438ca?)
      runtime/proc.go:363 +0xd6 fp=0xc001885750 sp=0xc001885730 pc=0x43d2b6
runtime.selectgo(0xc0018858f0, 0xc001e438c4, 0xc0000f27d8?, 0x0, 0x7fb5fa6ae5b8?, 0x1)
      runtime/select.go:328 +0x7bc fp=0xc001885890 sp=0xc001885750 pc=0x44d1fc
github.com/Azure/go-amqp.(*Receiver).Receive(0xc0004e0000, {0x77e54c8, 0xc000b5c400})
      github.com/Azure/go-amqp@v0.18.0/receiver.go:125 +0x212 fp=0xc0018859d8 sp=0xc001885890 pc=0x3461a72
```

**Comment by jhendrixMSFT** [comment]
- 1355 & 1742 - attempting to send a frame via conn.sendFrame() to connWriter which is dead
- 1353 - connReader() attempting to send a frame to conn.mux (conn.mux is blocked in 1752)
- 1752 - conn.mux attempting to send a frame to a session mux (presumably dead)
- 1354 - receiver.mux waiting for an incoming frame
- main thread - receiver.Receive() waiting

**Comment by jhendrixMSFT** [comment]
@mcardy how easy is this for you to repro?  I believe that some of these issues have been fixed (I need to fix the third bullet).

**Comment by mcardy** [comment]
It is not easy at all to reproduce. In our scenario, we send about 10 million messages to a receiver all the while connecting and disconnecting the socket. I can try with the head of main if that contains #173 and you think that is a potential fix?

**Comment by mcardy** [comment]
It looks like we are unable to reproduce this with the merge of #173. #218 also looks good to me to further reduce this possibility. Closing this as resolved by #173.

**Comment by mcardy** [comment]
Hey @jhendrixMSFT, happy new year! Not to sound like a broken record but do you have a target date for a release with #173 merged?

**Comment by jhendrixMSFT** [comment]
@mcardy happy new year!  Our POR is to get this, and other pending PRs, released within the next few weeks.
